"""add servicenow user mapping

Revision ID: 1e6f5fbbc139
Revises: 41958662dfda
Create Date: 2026-07-29 01:49:03.784696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e6f5fbbc139'
down_revision: Union[str, Sequence[str], None] = '41958662dfda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_approvals', 'servicenow_sync_status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('PENDING', 'SYNCED', 'FAILED', 'RETRYING', 'NOT_REQUIRED', name='servicenowsyncstatus', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_approvals', 'servicenow_sync_status',
               existing_type=sa.Enum('PENDING', 'SYNCED', 'FAILED', 'RETRYING', 'NOT_REQUIRED', name='servicenowsyncstatus', native_enum=False),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    # ### end Alembic commands ###
