"""add user approvals table

Revision ID: 5f383273eaee
Revises: 9f2317645b30
Create Date: 2026-07-21 14:51:20.403251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f383273eaee'
down_revision: Union[str, Sequence[str], None] = '9f2317645b30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_approvals',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approvalstatus', native_enum=False), nullable=False),
    sa.Column('approval_type', sa.Enum('MANUAL', 'AUTO', name='approvaltype', native_enum=False), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_approvals_status'), 'user_approvals', ['status'], unique=False)
    op.create_index(op.f('ix_user_approvals_user_id'), 'user_approvals', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_approvals_user_id'), table_name='user_approvals')
    op.drop_index(op.f('ix_user_approvals_status'), table_name='user_approvals')
    op.drop_table('user_approvals')
    # ### end Alembic commands ###
