"""add password hash to users

Revision ID: 8ca00006fe4c
Revises: 8e56d511f0f5
Create Date: 2026-07-04 22:52:30.381435

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8ca00006fe4c"
down_revision: Union[str, Sequence[str], None] = "8e56d511f0f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Step 1: Add the column as nullable
    op.add_column(
        "users",
        sa.Column(
            "password_hash",
            sa.String(length=255),
            nullable=True,
        ),
    )

    # Step 2: Give existing rows a temporary value
    op.execute("""
        UPDATE users
        SET password_hash = ''
        WHERE password_hash IS NULL
        """)

    # Step 3: Make the column NOT NULL
    op.alter_column(
        "users",
        "password_hash",
        nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "password_hash")
    # ### end Alembic commands ###
