"""add servicenow username to users

Revision ID: 98badac9f3a9
Revises: 8ca00006fe4c
Create Date: 2026-07-14 18:48:05.521229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98badac9f3a9'
down_revision: Union[str, Sequence[str], None] = '8ca00006fe4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('servicenow_username', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_users_servicenow_username'), 'users', ['servicenow_username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_servicenow_username'), table_name='users')
    op.drop_column('users', 'servicenow_username')
    # ### end Alembic commands ###
